# Generated by Django 4.0.4 on 2022-06-28 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_profile_nume_profile_prenume_alter_profile_telefon'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='data_created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
