# Generated by Django 4.0.4 on 2022-06-28 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_profile_data_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='adresa',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='telefon',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
