# Generated by Django 4.0.4 on 2022-06-28 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_profile_adresa_alter_profile_telefon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='adresa',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='nume',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='prenume',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='telefon',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
