# Generated by Django 4.0.4 on 2022-06-28 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_profile_adresa_alter_profile_nume_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='quote',
            name='suma',
            field=models.IntegerField(null=True),
        ),
    ]
