# Generated by Django 4.0.4 on 2022-06-29 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_alter_quote_suma'),
    ]

    operations = [
        migrations.AddField(
            model_name='quote',
            name='responded',
            field=models.BooleanField(default=False),
        ),
    ]
